export const homeObjOne = {
  id: "/om-meg",
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Om meg",
  description:
    "Noen kaller meg bare Ram. Jeg er fra Bergen og vokste opp med PC og internett. Jeg har alltid vært glad i data og teknologi og har vært nysgjerrig på hvordan de fungerer. Jeg har stor interesse for web-design og synes dette er veldig spennende og gøy. Det gjorde at jeg valgte min karriere som front-end utvikler. Jeg har hatt tidligere erfaringer med programmering. Blant annet har jeg laget en del prosjekter som Counter-APP, IMDB API søkemotor i React og en blogg side i Python Flask. Ved siden av driver jeg med musikk. Jeg spiller trommer, liker å gå turer og lese bøker. Som person er jeg behagelig å være med, liker å hjelpe andre mennesker og er samarbeidsvillig.",
  buttonLabel: "",
  imgStart: false,
  start: "",
  alt: "image",
  alt: "Vault",
  displayImage: true,
  img: require("./../../images/profile.jpg"),
  displayButton: false,
  visible: true,
};
export const homeObjTwo = {
  id: "/om-meg",
  primary: true,
  lightBg: true,
  lightTopLine: false,
  lightText: false,
  lightTextDesc: false,
  topLine: "",
  headline: "Om meg",
  description:
    "Noen kaller meg bare Ram. Jeg er fra Bergen og vokste opp med PC og internett. Jeg har alltid vært glad i data og teknologi og har vært nysgjerrig på hvordan de fungerer. Jeg har stor interesse for web-design og synes dette er veldig spennende og gøy. Det gjorde at jeg valgte min karriere som front-end utvikler. Jeg har hatt tidligere erfaringer med programmering. Blant annet har jeg laget en del prosjekter som Counter-APP, IMDB API søkemotor i React og en blogg side i Python Flask. Ved siden av driver jeg med musikk. Jeg spiller trommer, liker å gå turer og lese bøker. Som person er jeg behagelig å være med, liker å hjelpe andre mennesker og er samarbeidsvillig.",
  buttonLabel: "",
  imgStart: false,
  start: "",
  alt: "image",
  alt: "Vault",
  displayImage: true,
  img: require("./../../images/profile.jpg"),
  displayButton: false,
  visible: true,
};
